apiVersion: apps/v1
kind: Deployment
metadata: 
  name: helloworld
  labels:
    app: helloworld
spec: 
  replicas: 2
  selector: 
    matchLabels: 
      app: helloworld
  template: 
    metadata: 
      labels:
        app: helloworld
    spec: 
      containers: 
        - name: helloworld
          image: arjunksozone/helloworld:v2.0
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata: 
  name: helloworld
spec: 
  type: ClusterIP
  selector:
    app: helloworld
  ports: 
    - protocol: TCP
      port: 3000
      targetPort: 3000

